version: '3.8'

services:
  app-dev:
    build:
      context: .
      target: build
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_ENV=development
    container_name: belajar-react-dev