# Docker configuration commented out - not using Docker
# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "3000:80"
#     container_name: belajar-react-app
#     
#   dev:
#     build:
#       context: .
#       target: build
#     ports:
#       - "3001:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     command: npm start
#     container_name: belajar-react-dev
#     environment:
#       - CHOKIDAR_USEPOLLING=true