version: '3.8'

services:
  app-prod:
    build: .
    ports:
      - "80:80"
    environment:
      - REACT_APP_ENV=production
    container_name: belajar-react-prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3